-- Solo Teams - welcome_gui.lua
-- Author: bits-orio
-- License: MIT
--
-- Centered modal welcome screen.
--   • Auto-opens for brand-new players (online_time == 0 at on_player_created).
--   • Re-openable at any time via the [?] nav bar button.
--   • Esc closes it (player.opened = frame).
--
-- Tabs (native tabbed-pane, no custom click handlers needed)
--   About   - what Solo Teams is and how it works
--   Discord - QR code PNG + selectable invite URL
--
-- QR CODE
--   graphics/qr-code.png is a 504×256 mipmap sprite sheet (base 256×256) generated by:
--     python tools/gen_qr_matrix.py "https://discord.gg/tWz4FT74pH" --png
--   Registered as sprite "sb-qr-code" in data.lua.
--   Discord icon: graphics/discord-icon.png → sprite "sb-discord".

local nav = require("nav")

local M = {}

-- ---------------------------------------------------------------------------
-- Constants
-- ---------------------------------------------------------------------------

local DISCORD_URL = "https://discord.gg/tWz4FT74pH"
local NAV_BTN     = "sb_welcome_btn"
local FRAME_NAME  = "sb_welcome_frame"

-- ---------------------------------------------------------------------------
-- Tab: About
-- ---------------------------------------------------------------------------

local function draw_about(parent)
    local scroll = parent.add{
        type = "scroll-pane",
        vertical_scroll_policy = "auto-and-reserve-space",
        horizontal_scroll_policy = "never",
    }
    scroll.style.vertically_stretchable  = true
    scroll.style.left_padding            = 8
    scroll.style.right_padding           = 8
    scroll.style.top_padding             = 8
    scroll.style.bottom_padding          = 8

    local function section(title, body)
        local hdr = scroll.add{type = "label", caption = title}
        hdr.style.font          = "default-bold"
        hdr.style.font_color    = {r = 1, g = 0.82, b = 0.4}  -- warm gold
        hdr.style.single_line   = false
        hdr.style.top_margin    = 10
        hdr.style.bottom_margin = 3

        local txt = scroll.add{type = "label", caption = body}
        txt.style.single_line              = false
        txt.style.horizontally_stretchable = true
        txt.style.font_color               = {r = 0.9, g = 0.9, b = 0.9}
    end

    -- Tagline
    local tagline = scroll.add{type = "label",
        caption = "Solo by design. Legendary by choice."}
    tagline.style.font       = "default-large-semibold"
    tagline.style.font_color = {r = 0.6, g = 0.8, b = 1}
    tagline.style.top_margin = 4
    tagline.style.bottom_margin = 6

    section(
        "What is Solo Teams?",
        "Every player gets their own independent force. Research your own " ..
        "tech tree, build your own factory, and progress at your own pace, " ..
        "all on the same shared map."
    )
    section(
        "Forces & diplomacy",
        "Your personal force starts in cease-fire with all others. You can " ..
        "see each other's bases but can't accidentally damage them. " ..
        "Enable 'friend' in the Players panel to allow full cooperation."
    )
    section(
        "Navigation bar",
        "[img=utility/gps_map_icon] Players & Platforms - see all players and their locations\n" ..
        "[img=item/production-science-pack] Production Stats - compare your factory output\n" ..
        "[img=item/lab] Research - compare tech trees with a 1-on-1 diff view\n" ..
        "[img=virtual-signal/signal-info] This screen - reopen anytime"
    )
    section(
        "Landing Pen",
        "New players wait in the Landing Pen until they are ready to spawn. " ..
        "You can also buddy-up with a friend to start on the same planet."
    )
end

-- ---------------------------------------------------------------------------
-- Tab: Discord
-- ---------------------------------------------------------------------------

local function draw_discord(parent)
    local scroll = parent.add{
        type = "scroll-pane",
        vertical_scroll_policy = "auto-and-reserve-space",
        horizontal_scroll_policy = "never",
    }
    scroll.style.vertically_stretchable  = true
    scroll.style.horizontal_align        = "center"
    scroll.style.horizontally_stretchable = true
    scroll.style.left_padding            = 8
    scroll.style.right_padding           = 8
    scroll.style.top_padding             = 12
    scroll.style.bottom_padding          = 8

    -- Discord logo (icon + text in one image)
    local logo_row = scroll.add{type = "flow", direction = "horizontal"}
    logo_row.style.horizontal_align        = "center"
    logo_row.style.horizontally_stretchable = true
    logo_row.style.bottom_margin           = 8

    local logo = logo_row.add{type = "sprite", sprite = "sb-discord"}
    logo.style.width  = 280
    logo.style.height = 42
    logo.style.stretch_image_to_widget_size = true

    -- Subtitle
    local sub = scroll.add{type = "label",
        caption = "Scan the QR code or copy the invite link below."}
    sub.style.font_color               = {r = 0.75, g = 0.75, b = 0.75}
    sub.style.horizontal_align         = "center"
    sub.style.horizontally_stretchable = true
    sub.style.bottom_margin            = 12

    -- QR code image (registered in data.lua as "sb-qr-code")
    local qr_row = scroll.add{type = "flow", direction = "horizontal"}
    qr_row.style.horizontal_align        = "center"
    qr_row.style.horizontally_stretchable = true
    qr_row.style.bottom_margin           = 12

    local qr = qr_row.add{type = "sprite", sprite = "sb-qr-code"}
    qr.style.width  = 256
    qr.style.height = 256
    qr.style.stretch_image_to_widget_size = true

    -- Copyable invite URL
    local url_row = scroll.add{type = "flow", direction = "horizontal"}
    url_row.style.horizontal_align        = "center"
    url_row.style.horizontally_stretchable = true
    url_row.style.vertical_align          = "center"

    local tb = url_row.add{type = "text-box", text = DISCORD_URL}
    tb.read_only       = true
    tb.style.width     = 260
    tb.style.height    = 28
end

-- ---------------------------------------------------------------------------
-- Frame construction
-- ---------------------------------------------------------------------------

local function draw_frame(player)
    if player.gui.screen[FRAME_NAME] then return end
    local frame = player.gui.screen.add{
        type      = "frame",
        name      = FRAME_NAME,
        direction = "vertical",
    }
    frame.style.width  = 460
    frame.style.height = 560
    frame.auto_center  = true

    -- Title bar
    local title_bar = frame.add{type = "flow", direction = "horizontal"}
    title_bar.style.vertical_align = "center"
    title_bar.drag_target = frame
    title_bar.add{type = "label", caption = "Solo Teams", style = "frame_title"}
    local spacer = title_bar.add{type = "empty-widget", style = "draggable_space_header"}
    spacer.style.horizontally_stretchable = true
    spacer.style.height = 24
    spacer.drag_target = frame
    title_bar.add{
        type    = "sprite-button",
        name    = "sb_welcome_close",
        sprite  = "utility/close",
        style   = "close_button",
        tooltip = "Close",
    }

    -- Native tabbed pane (handles active/inactive tab styling automatically)
    local tabs = frame.add{type = "tabbed-pane", name = "sb_welcome_tabs"}
    tabs.style.horizontally_stretchable = true
    tabs.style.vertically_stretchable   = true
    tabs.style.top_margin               = 4

    -- Tab 1: About
    local about_tab = tabs.add{type = "tab", caption = "  About  "}
    local about_content = tabs.add{
        type      = "frame",
        direction = "vertical",
        style     = "inside_shallow_frame",
    }
    about_content.style.horizontally_stretchable = true
    about_content.style.vertically_stretchable   = true
    draw_about(about_content)
    tabs.add_tab(about_tab, about_content)

    -- Tab 2: Discord (icon in caption via rich text)
    local discord_tab = tabs.add{type = "tab", caption = "  Discord  "}
    local discord_content = tabs.add{
        type      = "frame",
        direction = "vertical",
        style     = "inside_shallow_frame",
    }
    discord_content.style.horizontally_stretchable = true
    discord_content.style.vertically_stretchable   = true
    draw_discord(discord_content)
    tabs.add_tab(discord_tab, discord_content)
    tabs.selected_tab_index = 1

    -- Allow Esc to close
    player.opened = frame
end

-- ---------------------------------------------------------------------------
-- Toggle / close
-- ---------------------------------------------------------------------------

local function toggle(event)
    local player = event.player
    local frame  = player.gui.screen[FRAME_NAME]
    if frame then
        frame.destroy()
    else
        draw_frame(player)
    end
end

-- ---------------------------------------------------------------------------
-- Public API
-- ---------------------------------------------------------------------------

--- Esc / on_gui_closed handler (called from control.lua)
function M.on_gui_closed(event)
    local player = game.get_player(event.player_index)
    if not player then return end
    local frame = player.gui.screen[FRAME_NAME]
    if frame and frame.valid then
        frame.destroy()
    end
end

--- Register the nav bar button and auto-open for brand-new players.
function M.on_player_created(player)
    nav.add_top_button(player, {
        name    = NAV_BTN,
        sprite  = "virtual-signal/signal-info",
        tooltip = "About Solo Teams / Discord",
    })
    nav.on_click(NAV_BTN, toggle)
    nav.on_click("sb_welcome_close", function(e)
        local frame = e.player.gui.screen[FRAME_NAME]
        if frame then frame.destroy() end
    end)

    -- Auto-open welcome screen for brand-new players only
    if player.online_time == 0 then
        draw_frame(player)
    end
end

return M
