#!/usr/bin/env python3
"""
Solo Teams — QR matrix generator
==================================
Generates the Lua QR_MATRIX / QR_SIZE block that gets pasted into
welcome_gui.lua whenever the Discord (or any other) URL changes.

Usage
-----
    python tools/gen_qr_matrix.py "https://discord.gg/YOURCODE"

Paste the printed output into welcome_gui.lua, replacing the existing
QR_MATRIX / QR_SIZE declarations near the top of the file.

Dependencies
------------
    pip install qrcode

Optional: --setup flag
    python tools/gen_qr_matrix.py --setup
Regenerates graphics/qr-black.png and graphics/qr-white.png (the two
minimal 1×1 pixel PNG sprites used by data.lua for QR cell rendering).
These are committed to source control and should not need regeneration
unless somehow lost.
"""

import sys
import os
import struct
import zlib


# ---------------------------------------------------------------------------
# Minimal 1×1 PNG helper (no external deps needed)
# ---------------------------------------------------------------------------

def _make_1x1_png(r: int, g: int, b: int) -> bytes:
    """Return raw bytes for a minimal valid 1×1 RGB PNG."""
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    sig  = b"\x89PNG\r\n\x1a\n"
    ihdr = chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0))
    # Scanline: filter byte (0 = None) followed by one RGB pixel
    idat = chunk(b"IDAT", zlib.compress(bytes([0, r, g, b])))
    iend = chunk(b"IEND", b"")
    return sig + ihdr + idat + iend


def setup_graphics() -> None:
    """Create/overwrite the two PNG assets required by data.lua."""
    script_dir   = os.path.dirname(os.path.abspath(__file__))
    graphics_dir = os.path.join(script_dir, "..", "graphics")
    os.makedirs(graphics_dir, exist_ok=True)

    black_path = os.path.join(graphics_dir, "qr-black.png")
    white_path = os.path.join(graphics_dir, "qr-white.png")

    with open(black_path, "wb") as f:
        f.write(_make_1x1_png(0, 0, 0))
    with open(white_path, "wb") as f:
        f.write(_make_1x1_png(255, 255, 255))

    print(f"Created {black_path}")
    print(f"Created {white_path}")


# ---------------------------------------------------------------------------
# QR matrix → Lua table
# ---------------------------------------------------------------------------

def generate_lua(url: str) -> str:
    try:
        import qrcode
    except ImportError:
        sys.exit("ERROR: 'qrcode' not installed.  Run:  pip install qrcode")

    qr = qrcode.QRCode(
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=1,
        border=4,
    )
    qr.add_data(url)
    qr.make(fit=True)

    matrix = qr.get_matrix()   # list of list of bool
    size   = len(matrix)

    lines = [
        f"-- Auto-generated by tools/gen_qr_matrix.py",
        f"-- URL: {url}  |  Size: {size}×{size}",
        f"-- To regenerate: python tools/gen_qr_matrix.py \"{url}\"",
        f"local QR_MATRIX = {{",
    ]
    for row in matrix:
        lines.append("    {" + ",".join("1" if c else "0" for c in row) + "},")
    lines.append("}")
    lines.append(f"local QR_SIZE = {size}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    args = sys.argv[1:]

    if not args:
        print(__doc__)
        sys.exit(1)

    if args[0] == "--setup":
        setup_graphics()
        sys.exit(0)

    url = args[0]
    print(generate_lua(url))
